### ISSUE TITLE
Delay in Github version docs getting synced up with the public facing docs?

### ISSUE THREAD

**Issue by ifaqeer-zz** [awsdocs/aws-site-to-site-vpn-user-guide#6]
@katerini Github version https://github.com/awsdocs/aws-site-to-site-vpn-user-guide/blob/master/doc_source/VPNTunnels.md don't match with https://docs.aws.amazon.com/vpn/latest/s2svpn/VPNTunnels.html?. The "Startup action" row in the table at the bottom is present in the public docs but missing the Github version. Thanks

**Comment by katerini** [comment]
Hi @ifaqeer - the GitHub docs have been updated now.

**Comment by ifaqeer-zz** [comment]
@katerini Thank you. However, the "Startup action" row in the Github still is does not match with the public docs for the same.

This is what the Github show:
The action to take when establishing the tunnel for a VPN connection. You can specify the following: [See the AWS documentation website for more details] For more information, see Site-to-Site VPN tunnel initiation options.

this is what the public docs show:
The action to take when establishing the tunnel for a VPN connection. You can specify the following:

    Start: AWS initiates the IKE negotiation to bring the tunnel up
    Add: Your customer gateway device must initiate the IKE negotiation to bring the tunnel up

For more information, see Site-to-Site VPN tunnel initiation options. 

Comparing the above two, we can see the difference and missing sentences in the Github version.

**Comment by katerini** [comment]
Unfortunately, this is a limitation of the GitHub docs. If there is formatting in the HTML pages that cannot be duplicated in markdown, our current workaround is to have a link that points to the HTML version. Sorry about this inconvenience.
